apiVersion: apps/v1
kind: Deployment
metadata:
  name: cks
  namespace: kubestronaut
  labels:
    app: cks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cks
  template:
    metadata:
      labels:
        app: cks
    spec:
      containers:
      - name: cks
        image: roko1987/cks
        ports:
        - containerPort: 8092