apiVersion: apps/v1
kind: Deployment
metadata:
  name: index
  namespace: kubestronaut
  labels:
    app: index
spec:
  replicas: 1
  selector:
    matchLabels:
      app: index
  template:
    metadata:
      labels:
        app: index
    spec:
      containers:
      - name: index
        image: roko1987/in
        ports:
        - containerPort: 80