apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcsa
  namespace: kubestronaut
  labels:
    app: kcsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcsa
  template:
    metadata:
      labels:
        app: kcsa
    spec:
      containers:
      - name: kcsa
        image: roko1987/kcsa
        ports:
        - containerPort: 8094