apiVersion: v1
kind: Namespace
metadata:
  name: kubestronaut
  labels:
    name: kubestronaut
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cka
  namespace: kubestronaut
  labels:
    app: cka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cka
  template:
    metadata:
      labels:
        app: cka
    spec:
      containers:
      - name: cka
        image: roko1987/cka
        ports:
        - containerPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckad
  namespace: kubestronaut
  labels:
    app: ckad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ckad
  template:
    metadata:
      labels:
        app: ckad
    spec:
      containers:
      - name: ckad
        image: roko1987/ckad
        ports:
        - containerPort: 8091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cks
  namespace: kubestronaut
  labels:
    app: cks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cks
  template:
    metadata:
      labels:
        app: cks
    spec:
      containers:
      - name: cks
        image: roko1987/cks
        ports:
        - containerPort: 8092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcna
  namespace: kubestronaut
  labels:
    app: kcna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcna
  template:
    metadata:
      labels:
        app: kcna
    spec:
      containers:
      - name: kcna
        image: roko1987/kcna
        ports:
        - containerPort: 8093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcsa
  namespace: kubestronaut
  labels:
    app: kcsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcsa
  template:
    metadata:
      labels:
        app: kcsa
    spec:
      containers:
      - name: kcsa
        image: roko1987/kcsa
        ports:
        - containerPort: 8094
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubestronaut
  namespace: kubestronaut
  labels:
    app: kubestronaut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubestronaut
  template:
    metadata:
      labels:
        app: kubestronaut
    spec:
      containers:
      - name: kubestronaut
        image: roko1987/kubestronaut
        ports:
        - containerPort: 8095
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: index
  namespace: kubestronaut
  labels:
    app: index
spec:
  replicas: 1
  selector:
    matchLabels:
      app: index
  template:
    metadata:
      labels:
        app: index
    spec:
      containers:
      - name: index
        image: roko1987/in
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cka
  namespace: kubestronaut
spec:
  type: ClusterIP
  selector:
    app: cka
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: ckad
  namespace: kubestronaut
spec:
  type: ClusterIP
  selector:
    app: ckad
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: cks
  namespace: kubestronaut
spec:
  type: ClusterIP
  selector:
    app: cks
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
---
apiVersion: v1
kind: Service
metadata:
  name: index
  namespace: kubestronaut
spec:
  type: LoadBalancer
  selector:
    app: index
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kcna
  namespace: kubestronaut
spec:
  type: ClusterIP
  selector:
    app: kcna
  ports:
    - protocol: TCP
      port: 8093
      targetPort: 8093
---
apiVersion: v1
kind: Service
metadata:
  name: kcsa
  namespace: kubestronaut
spec:
  type: ClusterIP
  selector:
    app: kcsa
  ports:
    - protocol: TCP
      port: 8094
      targetPort: 8094
---
apiVersion: v1
kind: Service
metadata:
  name: kubestronaut
  namespace: kubestronaut
spec:
  type: ClusterIP
  selector:
    app: kubestronaut
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
