apiVersion: v1
kind: Service
metadata:
  name: cka
  namespace: kubestronaut
spec:
  type: ClusterIP
  selector:
    app: cka
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091