apiVersion: v1
kind: Service
metadata:
  name: kcna
  namespace: kubestronaut
spec:
  type: ClusterIP
  selector:
    app: kcna
  ports:
    - protocol: TCP
      port: 8093
      targetPort: 8093