apiVersion: v1
kind: Service
metadata:
  name: kubestronaut
  namespace: kubestronaut
spec:
  type: ClusterIP
  selector:
    app: kubestronaut
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095