apiVersion: v1
kind: Service
metadata:
  name: index
  namespace: kubestronaut
spec:
  type: LoadBalancer
  selector:
    app: index
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80