apiVersion: v1
kind: Namespace
metadata:
  name: treasure
  labels:
    name: treasure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario
  labels:
    app: mario
spec:
  replicas: 0
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
      - name: mario-container
        image: sevenajay/mario:latest 
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - "apt-get update && apt-get install -y stress"
---
apiVersion: v1
kind: Service
metadata:
  name: mario-service
spec:
  type: LoadBalancer
  selector:
    app: treasure
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
