apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcd-ejercicio-1
  labels:
    app: kcd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kcd
  template:
    metadata:
      labels:
        app: kcd
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 88